baseurl: ""
name: "BOATHOUSE"
viewer: "Viewer"
description: "Надувные лодки ПВХ, байдарки и катамараны BOATHOUSE в 3D"
assets_path: ""
scripts: 
  - /assets/js/web/onw3d.js
  - /assets/js/local/main.js

compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
  startings: []

kramdown:
  input: GFM

sass:
  style: :compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - node_modules
  - scenes
  - package.json
  - package-lock.json
  - gulpfile.js
